FROM quay.io/refgenomics/docker-ubuntu:14.04
MAINTAINER Jenna Jensen  <jjensen24@kgi.edu>


RUN apt-get install -y samtools
RUN apt-get install -y bwa
RUN apt-get install -y bcftools
RUN apt-get install -y seqtk

# Convenience commands
ADD ../Scripts/Project_CRISPR copy 2.ipynb Project_CRISPR copy 2.ipynb
RUN chmod +x Project_CRISPR copy 2.ipynb

# Integration tests
ADD test /tmp/test
RUN bats /tmp/test

