FROM quay.io/refgenomics/docker-ubuntu:14.04
MAINTAINER Jenna Jensen  <jjensen24@kgi.edu>


RUN apt-get install -y samtools
RUN apt-get install -y bwa
RUN apt-get install -y bcftools
RUN apt-get install -y seqtk

# Convenience commands
ADD align.py /usr/local/bin/align.py
RUN chmod +x /usr/local/bin/align.py
RUN ln -s /usr/local/bin/align.py /usr/local/bin/align
CMD ["/usr/local/bin/align"]

# Integration tests
ADD test /tmp/test
RUN bats /tmp/test

